dcuolfg/missions/urls.py
# Copyright 2012 Deryck Hodge.  This software is licensed under the
# GNU Lesser General Public License version 3 (see the file LICENSE).

"""
URLS used for missions in dcuolfg.
"""

from django.conf.urls.defaults import (
    patterns,
    url,
)

from dcuolfg.missions.views import (
    location_index,
    mission_index,
)

urlpatterns = patterns('',
    url(
        r'locations/(?P<slug>[-\w]+)/$', location_index,
        name='location_index'),
    url(r'(?P<slug>[-\w]+)/$', mission_index, name='mission_index'),
)

dcuolfg/urls.py
# Copyright 2012-2013 Deryck Hodge.  This software is licensed under the
# GNU Lesser General Public License version 3 (see the file LICENSE).

"""
URLConf for MMOLFG sites.
"""

from django.conf import settings
from django.conf.urls.defaults import (
    include,
    patterns,
    url,
    )

from dcuolfg.views import (\
    dev,
    main,
    )

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^accounts/', include('dcuolfg.accounts.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/$', dev.api, name='api'),
    url(r'characters/', include('dcuolfg.characters.urls')),
    url(r'missions/', include('dcuolfg.missions.urls')),
    url(r'^$', main.index, name='home'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(
            r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                'document_root': settings.MEDIA_ROOT,
        }),
   )

dcuolfg/characters/models.py
# Copyright 2012-2013 Deryck Hodge.  This software is licensed under the
# GNU Lesser General Public License version 3 (see the file LICENSE).

"""
Models for characters in dcuolfg.
"""

import datetime

from django.contrib.auth.models import User
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from django.db import models
from django.utils.translation import ugettext_lazy as _

from dcuolfg.characters.managers import CharacterManager
from dcuolfg.missions.models import Mission


class Character(models.Model):
    """Characters used by Players in DCUO."""

    CHARACTER_SERVER_CHOICES = (
        (0, 'USPS3'),
        (1, 'USPC'),
        (2, 'EUPS3'),
        (3, 'EUPC'),
    )

    CHARACTER_ROLE_CHOICES = (
        (0, 'DPS'),
        (1, 'Controller'),
        (2, 'Healer'),
        (3, 'Tank'),
    )

    CHARACTER_POWERSET_CHOICES = (
        (0, 'Fire'),
        (1, 'Ice'),
        (2, 'Gadgets'),
        (3, 'Mental'),
        (4, 'Light'),
        (5, 'Socery'),
        (6, 'Nature'),
        (7, 'Electricity'),
    )

    player = models.ForeignKey(
        User, related_name='characters', verbose_name=_('player'))
    name = models.CharField(_('name'), max_length=75)
    server = models.IntegerField(
        _('server'), choices=CHARACTER_SERVER_CHOICES)
    role = models.IntegerField(_('role'), choices=CHARACTER_ROLE_CHOICES)
    powerset = models.IntegerField(
        _('powerset'), choices=CHARACTER_POWERSET_CHOICES)
    description = models.TextField(_('description'), blank=True,
        help_text=_('A short blurb describing your toon.'))
    level = models.IntegerField(
        _('level'), blank=True, null=True, default=1,
        validators=[MinValueValidator(0), MaxValueValidator(30)])
    combat_rating = models.IntegerField(
        _('combat_rating'), null=True, blank=True, default=0)
    skill_points = models.IntegerField(
        _('skill_points'), blank=True, null=True, default=0)
    league = models.CharField(_('league'), blank=True, max_length=100)
    image = models.ImageField(
        _('image'), upload_to='img/characters/%Y/%m/%d', blank=True)
    is_main = models.BooleanField(_('is_main'), default=False)
    lfg = models.BooleanField(_('lfg'), default=False)

    # The dates make use of auto_now and auto_now_add options, but
    # also include a "default" value.  This is so that Character objects
    # work sanely without having to call save on them.
    date_added = models.DateTimeField(
        _('date_added'), auto_now_add=True, auto_now=False,
        default=datetime.datetime.now)
    date_updated = models.DateTimeField(
        _('date_updated'), auto_now_add=True, auto_now=True,
        default=datetime.datetime.now)

    # Denormalized vote counts, to make it easier and faster
    # to get at the CharacterVote data.
    positive_votes = models.PositiveIntegerField(
        _('positive_votes'), default=0)
    negative_votes = models.PositiveIntegerField(
        _('negative_votes'), default=0)

    objects = CharacterManager()

    class Meta:
        """Metadata for Character model."""
        unique_together = ('server', 'name')
        db_table = 'character'
        get_latest_by = 'date_added'

    def __unicode__(self):
        """Used to describe each object in admin."""
        return u'%s: %s' % (self.get_server_display(), self.name)


class CharacterVote(models.Model):
    """Votes for or against a Character."""

    CHARACTER_VOTE_CHOICES = (
        (0, '-1'),
        (1, '+1'),
    )

    character = models.ForeignKey(
        Character, related_name='votes_for', verbose_name=_('character'))
    voter = models.ForeignKey(
        Character, related_name='votes_by', verbose_name=_('voter'))
    vote = models.IntegerField(_('vote'), choices=CHARACTER_VOTE_CHOICES)

    class Meta:
        """Metadata for CharacterVote model."""
        db_table = 'character_vote'

    def save(self, *args, **kwargs):
        """Override save to handle vote counting on Character."""
        super(CharacterVote, self).save(*args, **kwargs)
        if self.vote == 0:
            self.character.negative_votes += 1
        else:
            self.character.positive_votes += 1
        self.character.save()


class LFGRequest(models.Model):
    """The main object for tracking what Characters are LFG for."""

    LFG_CONTACT_CHOICES = (
        (0, 'In-game tell before invite.'),
        (1, 'Blind invites are fine.'),
        (2, 'See description for more details.'),
    )

    character = models.ForeignKey(
        Character, verbose_name=_('character'), related_name='requests')
    mission = models.ForeignKey(
        Mission, verbose_name=_('mission'), related_name='requests')
    description = models.TextField(_('description'), blank=True)
    contact_info = models.IntegerField(default=0, choices=LFG_CONTACT_CHOICES)

    class Meta:
        """Meta options for LFGRequest."""
        db_table = 'lfg_request'
        verbose_name = 'LFG Request'
        verbose_name_plural = 'LFG Requests'

    def __unicode__(self):
        """unicode representation of LFGRequest."""
        return u'LFG %s, for %s' % (self.character, self.mission)

dcuolfg/missions/models.py
# Copyright 2012 Deryck Hodge.  This software is licensed under the
# GNU Lesser General Public License version 3 (see the file LICENSE).

"""
Models for missions in DCUO LFG.
"""

from django.db import models
from django.utils.translation import ugettext_lazy as _

from dcuolfg.missions.managers import MissionManager


class Location(models.Model):
    """Mission Location object."""

    name = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField(
        _('image'), upload_to='img/locations/%Y/%m/%d', blank=True)

    class Meta:
        """Meta options for Location objects."""
        db_table = 'mission_location'

    def __unicode__(self):
        """unicode representation for Location"""
        return self.name


class Mission(models.Model):
    """Mission the base class for grouping together in DCUO LFG."""

    MISSION_TYPE_CHOICES = (
        (0, 'Areana PVP'),
        (1, 'Alert'),
        (2, 'Legends PVP'),
        (3, 'Raid'),
        (4, 'Duo'),
        (5, 'Bounty'),
        (6, 'Character leveling'),
        (7, 'Event'),
    )

    MISSION_MODE_CHOICES = (
        (0, 'Normal'),
        (1, 'T1'),
        (2, 'T2'),
    )

    MISSION_NUM_PLAYER_CHOICES = (
        (2, '2'),
        (4, '4'),
        (5, '5'),
        (8, '8'),
    )

    mission_type = models.IntegerField(
        _('mission type'), choices=MISSION_TYPE_CHOICES, default=1)
    mode = models.IntegerField(
        _('mode'), blank=True, null=True, choices=MISSION_MODE_CHOICES)
    name = models.CharField(_('name'), max_length=100)
    slug = models.SlugField()
    nick_name = models.CharField(_('nick name'), max_length=25)
    location = models.ForeignKey(
        Location, verbose_name=_('location'), related_name='missions')
    num_players = models.IntegerField(
        _('number of players'), choices=MISSION_NUM_PLAYER_CHOICES, default=4)
    about = models.TextField(_('about'), blank=True)
    featured = models.BooleanField(_('featured'), default=False)

    objects = MissionManager()

    class Meta():
        """Meta options for Mission."""
        db_table = 'mission'

    def __unicode__(self):
        """unicode representation of a Mission."""
        name = self.name
        location_name = self.location.name
        if name != location_name:
            full_name = '%s: %s' % (self.location.name, self.name)
        else:
            full_name = name
        return full_name

    @models.permalink
    def get_absolute_url(self):
        """Returns the URL for a Mission."""
        return ('mission_index', (), {'slug': self.slug})

dcuolfg/missions/views.py
# Copyright 2012 Deryck Hodge.  This software is licensed under the
# GNU Lesser General Public License version 3 (see the file LICENSE).

"""
Views for Mission and Location in dcuolfg.
"""

from django.shortcuts import (
    get_object_or_404,
    render,
)

from dcuolfg.missions.models import (
    Mission,
    Location,
)


def mission_index(request, slug):
    """Returns an index page for a Mission."""
    mission = get_object_or_404(Mission, slug=slug)
    data = {
        'mission': mission,
    }
    return render(request, 'missions/mission_index.html', data)


def location_index(request, slug):
    """Returns an index page for a Location."""
    location = get_object_or_404(Location, slug=slug)
    data = {
        'location': location,
    }
    return render(request, 'missions/location_index.html', data)

templates/missions/mission-lfg.html
<div class="mission-lfg">
    {% with mission.requests.count as count %}
    Currently {{ count }} player{{ count|pluralize }}
        LFG for this {{ mission.num_players }} person
    {{ mission.get_mission_type_display|lower }}.
    {% ifnotequal count 0  %}
        <div class="lfg-info">
            <div class="yui3-g lfg-heading">
                <div class="yui3-u-1-8">
                    <p>Character</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>Role</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>Powers</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>Level</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>CR</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>SP</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>Server</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>Contact info</p>
                </div>
            </div>
            {% for request in mission.requests.all  %}
            <div class="yui3-g lfg-row">
                {% with request.character as toon %}
                <div class="yui3-u-1-8">
                    <p>{{ toon.name }}</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>
                        {% ifequal toon.role 0 %}
                        <img
                        src="{{ STATIC_URL }}/img/dps.png"
                        title="DPS"
                        alt="DPS" />
                        {% endifequal %}
                        {% ifequal toon.role 1 %}
                        <img
                        src="{{ STATIC_URL }}/img/controller.png"
                        title="Controller"
                        alt="Controller" />
                        {% endifequal %}
                        {% ifequal toon.role 2 %}
                        <img
                        src="{{ STATIC_URL }}/img/healer.png"
                        title="Healer"
                        alt="Healer" />
                        {% endifequal %}
                        {% ifequal toon.role 3 %}
                        <img
                        title="Tank"
                        src="{{ STATIC_URL }}/img/tank.png"
                        alt="Tank" />
                        {% endifequal %}
                    </p>
                </div>
                <div class="yui3-u-1-8">
                    <p>{{ toon.get_powerset_display }}</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>{{ toon.level }}</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>{{ toon.combat_rating }}</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>{{ toon.skill_points }}</p>
                </div>
                <div class="yui3-u-1-8">
                    <p>{{ toon.get_server_display }}</p>
                </div>
                <div class="yui3-u-1-8">
                    {% with request.contact_info as contact %}
                    {% ifnotequal contact 2 %}
                    <p>{{ request.get_contact_info_display }}</p>
                    {% else %}
                    <p>{{ request.description }}</p>
                    {% endifnotequal %}
                    {% endwith %}
                </div>
                {% endwith %}
            </div>
            {% endfor %}
        </div> <!-- Close .lfg-info -->
    {% endifnotequal %}
    {% endwith %}
</div> <!-- Close .mission-lfg -->

templates/missions/mission_index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}
<div class="yui3-g blurb-row mission-index">
    <div class="yui3-u-1">
        <h2 class="headline">{{ mission }}</h2>
        <div class="yui3-g">
            <div class="yui3-u-1-4 mission-about">
               <img src="{{ MEDIA_URL }}{{ mission.location.image|thumbnail_url:'mission' }}"
                    alt="" />
                <div class="about">
                    {{ mission.about }}
                </div>
            </div>
            <div class="yui3-u-3-4">
                {% include "missions/mission-lfg.html" %}
                <p class="promo">If you would like to register yourself
                    as LFG for {{ mission }}, please
                    <a href="/accounts/register/">create an account</a>
                    or <a href="/accounts/login/">login</a>.</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}